push = require 'lib/push'
Class = require 'lib/class'

require 'src/Animation'
require 'src/Dad'
require 'src/Entity'
require 'src/LightSource'
require 'src/Objects'
require 'src/Player'
require 'src/Sprites'